# Set the base image
FROM mcr.microsoft.com/windows:ltsc2019

# Loop through the port range
EXPOSE 6969

# Create the directory if it doesn't exist (optional)
RUN mkdir C:\\app

# Set the working directory
WORKDIR C:\\app

# Define the custom installation directory
ENV PYTHON_INSTALL_DIR="\\Python3"

# Download Python 3.11 installer from the official Python website
ADD https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe python-installer\\python-3.11.0.exe

# Install Python 3.11 to the custom directory (/quiet)
RUN python-installer\\python-3.11.0.exe /quiet TargetDir="C:\\Python3"

# Debugging: Check the existence of the Python installation directory using PowerShell
RUN powershell -Command "Get-ChildItem -Path C:\\"

# Manually add Python to PATH and verify Python installation
RUN setx PATH "%PATH%;C:\Python3" /M
ENV PATH="%PATH%;C:\Python3"

# Check Python version
RUN python --version

# Copy the current directory contents into the container at /app
COPY . .

# Set the entrypoint command to run your Python script
ENTRYPOINT [ "python", "Game/src/code/security_server.py" ]
