# Dockerfile for main server
FROM python:3.11-slim-bullseye

# Expose ports 80-65535
EXPOSE 80-500

# Set the working directory
WORKDIR /app

# Copy the game script
COPY . .

# Install dependencies
RUN pip install -r /app/requirements.txt
RUN pip install https://github.com/secdev/scapy/archive/refs/heads/master.zip

# Run the game script
CMD ["python" , "Game/src/code/the_server.py"]

