version: '3.8'

services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile-2
    image: basic_com-load_balancer
    container_name: load_balancer
    ports:
      - "1800:1800/tcp"
    tty: true
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
    name: my-network
    external: false