version: '3.8'

services:
  the-server:
    image: cat69/cyber_offensive:server
    container_name: server
    ports:
      - "8820:8820/tcp"
      - "6921:6921/tcp"
      - "8843:8843/tcp"
      - "443:443/tcp"
    tty: true
    volumes:
      - server:/app/Game/src/code/Database
    networks:
      - my-network
    environment:
<<<<<<< HEAD
      - LOAD_BALANCER_IP=192.168.56.1 # Assuming container name is "load_balancer"
=======
<<<<<<< HEAD
      - LOAD_BALANCER_IP=192.168.56.1 # Assuming container name is "load_balancer"
=======
      - LOAD_BALANCER_IP=load_balancer # Assuming container name is "load_balancer"
>>>>>>> 3caee80555e51bc5f10399bdfe5d4e3deefc6b01
>>>>>>> f9bad6d2c4158006b1b28baf5903bb84d1b43ea4

volumes:
  server:
    driver: local

networks:
  my-network:
    name: my-network
    external: true
