# Dockerfile for security server
FROM python:3.11-slim-bullseye

# Expose ports 443-500
EXPOSE 443-500
EXPOSE 53

# Set the working directory
WORKDIR /app

# Copy the security server script
COPY . .

# Install dependencies
RUN pip install -r /app/requirements.txt
RUN pip install https://github.com/secdev/scapy/archive/refs/heads/master.zip

# Run the security server script
CMD ["python", "Game/src/code/security_server.py"]
