version: '3.8'

services:
  load_balancer:
    image: cat69/cyber_offensive:load_balancer
    container_name: load_balancer
    ports:
      - "1800:1800/tcp"
    tty: true
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
    name: my-network
    external: false