version: '3.8'
services:
  the-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: basic_com-server
    container_name: server
    ports:
      - "8820:8820/tcp"
      - "6921:6921/tcp"
      - "8843:8843/tcp"
      - "443:443/tcp"
      - "1800:1800/tcp"
    tty: true
  
  dnssec_server:
    build:
      context: .
      dockerfile: Dockerfile-2
    image: basic_com-dnssec_server
    container_name: dnssec_server
    ports:
      - "5353:5353/udp"
      - "53:53/udp"
    tty: true
