version: '3.8'

services:
  the-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: basic_com-server
    container_name: server
    ports:
      - "8820:8820/tcp"
      - "6921:6921/tcp"
      - "8843:8843/tcp"
      - "443:443/tcp"
    tty: true
    volumes:
      - server:/app/Game/src/code/Database
    networks:
      - my-network
    environment:
      - LOAD_BALANCER_IP=10.0.0.7  # Assuming container name is "load_balancer"

volumes:
  server:
    driver: local

networks:
  my-network:
    name: my-network
    external: true
